version: '3'
services:
  db: 
      image: mongo
      restart: always
      ports: 
        - 27017:27017
  api:
    build: server
    restart: always
  nginx:
    build: client
    restart: always
    ports:
      - 8080:80